// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBvfk_9Nwy15XEUjfHJKIe8PFzeMND1eeQ',
    appId: '1:522116239438:web:6a3861b1b47d480b3c731f',
    messagingSenderId: '522116239438',
    projectId: 'appdevquiz-d239b',
    authDomain: 'appdevquiz-d239b.firebaseapp.com',
    storageBucket: 'appdevquiz-d239b.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDAUXZl_Cb_5VRt5Qv_5Hwf1jvHeps_9fU',
    appId: '1:522116239438:android:d6dff999adc5f4cd3c731f',
    messagingSenderId: '522116239438',
    projectId: 'appdevquiz-d239b',
    storageBucket: 'appdevquiz-d239b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA3rLBAnuZSB0xtsw-aCQhal7RzFuqdhCA',
    appId: '1:522116239438:ios:0191c761bbe1a61f3c731f',
    messagingSenderId: '522116239438',
    projectId: 'appdevquiz-d239b',
    storageBucket: 'appdevquiz-d239b.firebasestorage.app',
    iosBundleId: 'com.example.appDevQuizQ2Q3',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA3rLBAnuZSB0xtsw-aCQhal7RzFuqdhCA',
    appId: '1:522116239438:ios:0191c761bbe1a61f3c731f',
    messagingSenderId: '522116239438',
    projectId: 'appdevquiz-d239b',
    storageBucket: 'appdevquiz-d239b.firebasestorage.app',
    iosBundleId: 'com.example.appDevQuizQ2Q3',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBvfk_9Nwy15XEUjfHJKIe8PFzeMND1eeQ',
    appId: '1:522116239438:web:999d6595724325203c731f',
    messagingSenderId: '522116239438',
    projectId: 'appdevquiz-d239b',
    authDomain: 'appdevquiz-d239b.firebaseapp.com',
    storageBucket: 'appdevquiz-d239b.firebasestorage.app',
  );
}
